# Traefik ACME Configuration for K3s
# Place this file in: /var/lib/rancher/k3s/server/manifests/traefik-config.yaml

apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    # ACME / Let's Encrypt configuration
    additionalArguments:
      - "--certificatesresolvers.letsencrypt.acme.email=artur.komarovv@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--log.level=INFO"
      - "--accesslog=true"
    
    # Port configuration
    ports:
      web:
        exposedPort: 80
        redirectTo: websecure
      websecure:
        exposedPort: 443
        tls:
          enabled: true
    
    # Persistence for ACME certificates
    persistence:
      enabled: true
      path: /data
      size: 1Gi
    
    # Global redirect HTTP to HTTPS
    globalArguments:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"